language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_script: gradle setupCIWorkspace
script: gradle build
notifications:
  irc: "irc.esper.net#AlternativeEnergy"
  irc: "irc.reening.nl#server"
